const translations = {
  es: {
    skip: "Saltar al contenido", navLabel: "Navegación principal", logoHome: "El Hornero, inicio", galleryDialog: "Galería de imágenes", deltaLandscape: "Paisaje del Delta", routeLabel: "Buenos Aires, Tigre Centro, lancha, Tres Bocas, Arroyo Abra Vieja, El Hornero", home: "Inicio", experience: "Experiencia", menu: "Menú", gallery: "Galería", directions: "Cómo llegar",
    language: "Elegir idioma", openMenu: "Abrir menú", closeMenu: "Cerrar menú", heroKicker: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja", heroLine: "Una mesa entre el río y el verde.", viewMenu: "Ver menú", getThere: "Cómo llegar",
    expEyebrow: "01 — Experiencia", expTitle: "El Delta, servido a su propio ritmo.", expBody: "Comida, madera, vegetación y aire de río se encuentran en Tres Bocas. El Hornero propone una pausa simple dentro del paisaje del Delta.", expNote: "Un lugar para quedarse un rato",
    breakPhrase: "Entre glicinas, madera y luz del Delta.",
    galleryEyebrow: "02 — Cuaderno de campo", galleryTitle: "Postales de Tres Bocas", galleryIntro: "Una mirada a los sabores, el paisaje y los pequeños detalles que rodean la mesa.", viewImage: "Abrir imagen",
    catPlace: "El lugar", catFood: "Comida", catDelta: "Delta", catDetails: "Detalles", catAtmosphere: "Atmósfera",
    altHero: "Ilustración reemplazable de una mesa exterior bajo vegetación en el Delta", altTable: "Ilustración reemplazable de una mesa de madera entre glicinas", altFood: "Ilustración reemplazable de una presentación de comida sobre cerámica", altRiver: "Ilustración reemplazable del río y una lancha entre juncos", altPath: "Ilustración reemplazable de un sendero de Tres Bocas entre vegetación", altDetail: "Ilustración reemplazable de texturas de madera, hojas y luz", altTerrace: "Ilustración reemplazable de mesas al aire libre bajo árboles", altBoat: "Ilustración reemplazable de una lancha cruzando el Delta", altLight: "Ilustración reemplazable de luz filtrándose entre glicinas", altMenu: "Ilustración reemplazable de una mesa preparada junto a hojas verdes",
    lbClose: "Cerrar galería", lbPrev: "Imagen anterior", lbNext: "Imagen siguiente",
    menuEyebrow: "03 — La carta", menuTitle: "Comer entre verde", menuIntro: "Conocé nuestra carta de ejemplo y sus categorías.", openFullMenu: "Abrir menú completo", menuEmpty: "La carta todavía no fue cargada.", menuEmptyHint: "Consultá en el lugar por la propuesta disponible.",
    journeyEyebrow: "Guía de viaje", journeyTitle: "Del Buenos Aires urbano al Delta", journeyBody: "Desde Palermo, San Telmo, Microcentro o La Boca, el paisaje cambia al acercarse a Tigre. Desde allí, la lancha continúa hacia Tres Bocas, sobre el Arroyo Abra Vieja.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centro", boat: "Lancha", riverStation: "Estación fluvial", tresBocas: "Tres Bocas", abraVieja: "Arroyo Abra Vieja", hornero: "El Hornero",
    directionsEyebrow: "04 — Cómo llegar", directionsTitle: "El camino también es parte del paseo.", directionsBody: "Llegá a Tigre y continuá por agua hacia Tres Bocas, sobre el Arroyo Abra Vieja. Verificá recorridos, frecuencias y disponibilidad con los operadores antes de viajar.", mitre: "Tren Mitre", mitreDesc: "Desde Retiro hasta la estación Tigre.", coast: "Tren de la Costa", coastDesc: "Llegá hasta la estación Delta, en Tigre.", car: "Auto", carDesc: "Llegá por tierra hasta Tigre y continuá el recorrido desde allí.", boatOption: "Lancha", boatDesc: "Embarcá hacia Tres Bocas desde la estación fluvial.", viewStation: "Ver estación", viewRiverStation: "Ver estación fluvial", maps: "Abrir en Google Maps", transportNote: "Los servicios pueden cambiar. Confirmá la información de viaje antes de salir.",
    instagramTitle: "El Delta, en imágenes", instagramCta: "Ver Instagram", footerLine: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja · Buenos Aires", backHome: "Volver al inicio", menuPageTitle: "Menú", menuPageIntro: "Nuestra carta digital", menuUpdated: "Contenido configurable", menuSample: "Menú de muestra", menuSampleNote: "Los platos, ingredientes y disponibilidad de esta carta son de ejemplo y deben confirmarse con el restaurante.", noScript: "Activá JavaScript para utilizar el selector de idioma y la galería."
  },
  en: {
    skip: "Skip to content", navLabel: "Main navigation", logoHome: "El Hornero, home", galleryDialog: "Image gallery", deltaLandscape: "Delta landscape", routeLabel: "Buenos Aires, Tigre Centre, boat, Tres Bocas, Abra Vieja stream, El Hornero", home: "Home", experience: "Experience", menu: "Menu", gallery: "Gallery", directions: "Directions",
    language: "Choose language", openMenu: "Open menu", closeMenu: "Close menu", heroKicker: "Tigre Delta · Tres Bocas · Abra Vieja stream", heroLine: "A table between the river and the green.", viewMenu: "View menu", getThere: "Get directions",
    expEyebrow: "01 — Experience", expTitle: "The Delta, served at its own pace.", expBody: "Food, wood, vegetation and river air meet in Tres Bocas. El Hornero offers a simple pause within the Delta landscape.", expNote: "A place to stay awhile",
    breakPhrase: "Among wisteria, wood and Delta light.",
    galleryEyebrow: "02 — Field notes", galleryTitle: "Postcards from Tres Bocas", galleryIntro: "A glimpse of the flavours, landscape and small details surrounding the table.", viewImage: "Open image",
    catPlace: "The place", catFood: "Food", catDelta: "Delta", catDetails: "Details", catAtmosphere: "Atmosphere",
    altHero: "Replaceable illustration of an outdoor table under Delta vegetation", altTable: "Replaceable illustration of a wooden table among wisteria", altFood: "Replaceable illustration of food presented on ceramic", altRiver: "Replaceable illustration of the river and a boat among reeds", altPath: "Replaceable illustration of a Tres Bocas path through vegetation", altDetail: "Replaceable illustration of wood, leaves and light textures", altTerrace: "Replaceable illustration of outdoor tables under trees", altBoat: "Replaceable illustration of a boat crossing the Delta", altLight: "Replaceable illustration of light filtering through wisteria", altMenu: "Replaceable illustration of a set table beside green leaves",
    lbClose: "Close gallery", lbPrev: "Previous image", lbNext: "Next image",
    menuEyebrow: "03 — The menu", menuTitle: "Dining among the green", menuIntro: "Explore our sample menu and its categories.", openFullMenu: "Open full menu", menuEmpty: "The menu has not been uploaded yet.", menuEmptyHint: "Please ask at the restaurant about today's selection.",
    journeyEyebrow: "Travel guide", journeyTitle: "From urban Buenos Aires to the Delta", journeyBody: "From Palermo, San Telmo, Microcentro or La Boca, the scenery changes as you approach Tigre. From there, continue by boat towards Tres Bocas, along the Abra Vieja stream.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centre", boat: "Boat", riverStation: "River station", tresBocas: "Tres Bocas", abraVieja: "Abra Vieja stream", hornero: "El Hornero",
    directionsEyebrow: "04 — Directions", directionsTitle: "The journey is part of the outing.", directionsBody: "Reach Tigre and continue by water towards Tres Bocas, on the Abra Vieja stream. Check routes, schedules and availability with operators before travelling.", mitre: "Mitre train", mitreDesc: "Travel from Retiro to Tigre station.", coast: "Tren de la Costa", coastDesc: "Travel to Delta station in Tigre.", car: "Car", carDesc: "Travel overland to Tigre and continue the route from there.", boatOption: "Boat", boatDesc: "Board for Tres Bocas at the river station.", viewStation: "View station", viewRiverStation: "View river station", maps: "Open in Google Maps", transportNote: "Services may change. Confirm travel information before setting out.",
    instagramTitle: "The Delta, in pictures", instagramCta: "View Instagram", footerLine: "Tigre Delta · Tres Bocas · Abra Vieja stream · Buenos Aires", backHome: "Back to home", menuPageTitle: "Menu", menuPageIntro: "Our digital menu", menuUpdated: "Configurable content", menuSample: "Sample menu", menuSampleNote: "The dishes, ingredients and availability on this menu are examples and should be confirmed with the restaurant.", noScript: "Enable JavaScript to use language selection and the gallery."
  },
  pt: {
    skip: "Pular para o conteúdo", navLabel: "Navegação principal", logoHome: "El Hornero, início", galleryDialog: "Galeria de imagens", deltaLandscape: "Paisagem do Delta", routeLabel: "Buenos Aires, Tigre Centro, lancha, Tres Bocas, Arroyo Abra Vieja, El Hornero", home: "Início", experience: "Experiência", menu: "Cardápio", gallery: "Galeria", directions: "Como chegar",
    language: "Escolher idioma", openMenu: "Abrir menu", closeMenu: "Fechar menu", heroKicker: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja", heroLine: "Uma mesa entre o rio e o verde.", viewMenu: "Ver cardápio", getThere: "Como chegar",
    expEyebrow: "01 — Experiência", expTitle: "O Delta, servido no seu próprio ritmo.", expBody: "Comida, madeira, vegetação e ar de rio se encontram em Tres Bocas. El Hornero propõe uma pausa simples dentro da paisagem do Delta.", expNote: "Um lugar para ficar um pouco",
    breakPhrase: "Entre glicínias, madeira e luz do Delta.",
    galleryEyebrow: "02 — Caderno de campo", galleryTitle: "Postais de Tres Bocas", galleryIntro: "Um olhar sobre os sabores, a paisagem e os pequenos detalhes ao redor da mesa.", viewImage: "Abrir imagem",
    catPlace: "O lugar", catFood: "Comida", catDelta: "Delta", catDetails: "Detalhes", catAtmosphere: "Atmosfera",
    altHero: "Ilustração substituível de uma mesa externa sob a vegetação do Delta", altTable: "Ilustração substituível de uma mesa de madeira entre glicínias", altFood: "Ilustração substituível de comida apresentada em cerâmica", altRiver: "Ilustração substituível do rio e uma lancha entre juncos", altPath: "Ilustração substituível de uma trilha de Tres Bocas entre vegetação", altDetail: "Ilustração substituível de texturas de madeira, folhas e luz", altTerrace: "Ilustração substituível de mesas ao ar livre sob árvores", altBoat: "Ilustração substituível de uma lancha atravessando o Delta", altLight: "Ilustração substituível de luz filtrada pelas glicínias", altMenu: "Ilustração substituível de uma mesa preparada junto a folhas verdes",
    lbClose: "Fechar galeria", lbPrev: "Imagem anterior", lbNext: "Próxima imagem",
    menuEyebrow: "03 — O cardápio", menuTitle: "Comer entre o verde", menuIntro: "Conheça nosso cardápio de exemplo e suas categorias.", openFullMenu: "Abrir cardápio completo", menuEmpty: "O cardápio ainda não foi carregado.", menuEmptyHint: "Consulte no local a proposta disponível.",
    journeyEyebrow: "Guia de viagem", journeyTitle: "Da Buenos Aires urbana ao Delta", journeyBody: "De Palermo, San Telmo, Microcentro ou La Boca, a paisagem muda ao se aproximar de Tigre. De lá, a lancha continua até Tres Bocas, pelo Arroyo Abra Vieja.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centro", boat: "Lancha", riverStation: "Estação fluvial", tresBocas: "Tres Bocas", abraVieja: "Arroyo Abra Vieja", hornero: "El Hornero",
    directionsEyebrow: "04 — Como chegar", directionsTitle: "O caminho também faz parte do passeio.", directionsBody: "Chegue a Tigre e continue pela água até Tres Bocas, no Arroyo Abra Vieja. Verifique rotas, frequências e disponibilidade com os operadores antes de viajar.", mitre: "Trem Mitre", mitreDesc: "Viaje de Retiro até a estação Tigre.", coast: "Tren de la Costa", coastDesc: "Viaje até a estação Delta, em Tigre.", car: "Carro", carDesc: "Chegue por terra até Tigre e continue o percurso de lá.", boatOption: "Lancha", boatDesc: "Embarque para Tres Bocas na estação fluvial.", viewStation: "Ver estação", viewRiverStation: "Ver estação fluvial", maps: "Abrir no Google Maps", transportNote: "Os serviços podem mudar. Confirme as informações de viagem antes de sair.",
    instagramTitle: "O Delta, em imagens", instagramCta: "Ver Instagram", footerLine: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja · Buenos Aires", backHome: "Voltar ao início", menuPageTitle: "Cardápio", menuPageIntro: "Nosso cardápio digital", menuUpdated: "Conteúdo configurável", menuSample: "Cardápio de exemplo", menuSampleNote: "Os pratos, ingredientes e a disponibilidade deste cardápio são exemplos e devem ser confirmados com o restaurante.", noScript: "Ative o JavaScript para usar o seletor de idioma e a galeria."
  }
};
