const translations = {
  es: {
    skip: "Saltar al contenido", navLabel: "Navegación principal", logoHome: "El Hornero, inicio", galleryDialog: "Galería de imágenes", deltaLandscape: "Paisaje del Delta", routeLabel: "Buenos Aires, Tigre Centro, lancha, Tres Bocas, Arroyo Abra Vieja, El Hornero", home: "Inicio", experience: "Experiencia", menu: "Menú", gallery: "Galería", directions: "Cómo llegar",
    language: "Elegir idioma", openMenu: "Abrir menú", closeMenu: "Cerrar menú", heroKicker: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja", heroLine: "Una mesa entre el río y el verde.", viewMenu: "Ver menú", getThere: "Cómo llegar",
    expEyebrow: "01 — Experiencia", expTitle: "El Delta, servido a su propio ritmo.", expBody: "Comida, madera, vegetación y aire de río se encuentran en Tres Bocas. El Hornero propone una pausa simple dentro del paisaje del Delta.", expNote: "Un lugar para quedarse un rato",
    breakPhrase: "Entre glicinas, madera y luz del Delta.",
    galleryEyebrow: "02 — Cuaderno de isla", galleryTitle: "Postales de Tres Bocas", galleryIntro: "Una mirada a los sabores, el paisaje y los pequeños detalles que rodean la mesa.", viewImage: "Abrir imagen",
    catPlace: "El lugar", catFood: "Comida", catDelta: "Delta", catDetails: "Detalles", catAtmosphere: "Atmósfera",
    altHero: "Mesa exterior de El Hornero entre la vegetación del Delta de Tigre", altTable: "Espacio exterior de El Hornero junto al río en el Delta", altFood: "Plato servido en El Hornero, restaurante del Delta", altRiver: "Paisaje del río en el Delta de Tigre junto a El Hornero", altPath: "Vegetación y senderos del Delta de Tigre", altDetail: "Detalles de madera, vegetación y luz en El Hornero", altTerrace: "Mesas al aire libre bajo los árboles del Delta", altBoat: "Lancha navegando por el Delta de Tigre", altPrivateBoat: "Pasajeros viajando en una lancha por el Delta", altPrivateDestination: "Grupo de visitantes en El Hornero", altLight: "Luz entre glicinas, madera y vegetación del Delta", altMenu: "Plato de la carta de El Hornero en el Delta", altGalleryPhoto: "Fotografía de El Hornero, restaurante en el Delta de Tigre", altRouteMap: "Mapa de acceso a Tres Bocas y El Hornero desde Tigre",
    lbClose: "Cerrar galería", lbPrev: "Imagen anterior", lbNext: "Imagen siguiente",
    menuEyebrow: "03 — La carta", menuTitle: "Comer entre verde", menuIntro: "Conocé nuestra carta de ejemplo y sus categorías.", openFullMenu: "Abrir menú completo", menuEmpty: "La carta todavía no fue cargada.", menuEmptyHint: "Consultá en el lugar por la propuesta disponible.",
    journeyEyebrow: "Guía de viaje", journeyTitle: "Del Buenos Aires urbano al Delta", journeyBody: "Desde Palermo, San Telmo, Microcentro o La Boca, el paisaje cambia al acercarse a Tigre. Desde allí, la lancha continúa hacia Tres Bocas, sobre el Arroyo Abra Vieja.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centro", boat: "Lancha", riverStation: "Estación fluvial", tresBocas: "Tres Bocas", abraVieja: "Arroyo Abra Vieja", hornero: "El Hornero",
    directionsEyebrow: "04 — Cómo llegar", directionsTitle: "El camino también es parte del paseo.", directionsBody: "Llegá a Tigre y continuá por agua hacia Tres Bocas, sobre el Arroyo Abra Vieja. Verificá recorridos, frecuencias y disponibilidad con los operadores antes de viajar.", routeMapCaption: "Mapa de acceso a Tres Bocas", mitre: "Tren Mitre", mitreDesc: "Desde Retiro hasta la estación Tigre.", coast: "Tren de la Costa", coastDesc: "Llegá hasta la estación Delta, en Tigre.", car: "Auto", carDesc: "Llegá por tierra hasta Tigre y continuá el recorrido desde allí.", boatOption: "Lancha Pública", boatDesc: "Interisleña · Boleterías 3 y 4 · Bajarse en Tres Bocas", boatPhone: "Teléfono: 4749-0900", privateBoat: "Lancha Remis", privateBoatDesc: "Coordiná un traslado privado hacia Tres Bocas.", privateBoatCta: "Coordinar por WhatsApp", privateTransferEyebrow: "El viaje también es parte del plan", privateTransferTitle: "Llegá por el río, a tu ritmo.", privateTransferBody: "Coordiná una lancha remis para llegar a Tres Bocas de forma directa y disfrutar el paisaje desde el primer momento. Consultanos por disponibilidad y organizamos el viaje con vos.", privateTransferCta: "Consultar traslado privado", viewStation: "Ver estación", viewRiverStation: "Ver estación fluvial", maps: "Abrir en Google Maps", transportNote: "Los servicios pueden cambiar. Confirmá la información de viaje antes de salir.",
    instagramTitle: "El Delta, en imágenes", instagramCta: "Ver Instagram", footerLine: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja · Buenos Aires", backHome: "Volver al inicio", menuPageTitle: "Menú", menuPageIntro: "Nuestra carta digital", menuUpdated: "Contenido configurable", menuSample: "Menú de muestra", menuSampleNote: "Los platos, ingredientes y disponibilidad de esta carta son de ejemplo y deben confirmarse con el restaurante.", noScript: "Activá JavaScript para utilizar el selector de idioma y la galería."
  },
  en: {
    skip: "Skip to content", navLabel: "Main navigation", logoHome: "El Hornero, home", galleryDialog: "Image gallery", deltaLandscape: "Delta landscape", routeLabel: "Buenos Aires, Tigre Centre, boat, Tres Bocas, Abra Vieja stream, El Hornero", home: "Home", experience: "Experience", menu: "Menu", gallery: "Gallery", directions: "Directions",
    language: "Choose language", openMenu: "Open menu", closeMenu: "Close menu", heroKicker: "Tigre Delta · Tres Bocas · Abra Vieja stream", heroLine: "A table between the river and the green.", viewMenu: "View menu", getThere: "Get directions",
    expEyebrow: "01 — Experience", expTitle: "The Delta, served at its own pace.", expBody: "Food, wood, vegetation and river air meet in Tres Bocas. El Hornero offers a simple pause within the Delta landscape.", expNote: "A place to stay awhile",
    breakPhrase: "Among wisteria, wood and Delta light.",
    galleryEyebrow: "02 — Field notes", galleryTitle: "Postcards from Tres Bocas", galleryIntro: "A glimpse of the flavours, landscape and small details surrounding the table.", viewImage: "Open image",
    catPlace: "The place", catFood: "Food", catDelta: "Delta", catDetails: "Details", catAtmosphere: "Atmosphere",
    altHero: "El Hornero outdoor table among vegetation in the Tigre Delta", altTable: "El Hornero outdoor space beside the river in the Delta", altFood: "Dish served at El Hornero restaurant in the Delta", altRiver: "River landscape in the Tigre Delta near El Hornero", altPath: "Vegetation and paths in the Tigre Delta", altDetail: "Wood, vegetation and light details at El Hornero", altTerrace: "Outdoor tables under Delta trees", altBoat: "Boat navigating the Tigre Delta", altPrivateBoat: "Passengers travelling by boat through the Delta", altPrivateDestination: "A group of visitors at El Hornero", altLight: "Light among wisteria, wood and Delta vegetation", altMenu: "Dish from El Hornero menu in the Delta", altGalleryPhoto: "Photograph of El Hornero restaurant in the Tigre Delta", altRouteMap: "Map showing access to Tres Bocas and El Hornero from Tigre",
    lbClose: "Close gallery", lbPrev: "Previous image", lbNext: "Next image",
    menuEyebrow: "03 — The menu", menuTitle: "Dining among the green", menuIntro: "Explore our sample menu and its categories.", openFullMenu: "Open full menu", menuEmpty: "The menu has not been uploaded yet.", menuEmptyHint: "Please ask at the restaurant about today's selection.",
    journeyEyebrow: "Travel guide", journeyTitle: "From urban Buenos Aires to the Delta", journeyBody: "From Palermo, San Telmo, Microcentro or La Boca, the scenery changes as you approach Tigre. From there, continue by boat towards Tres Bocas, along the Abra Vieja stream.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centre", boat: "Boat", riverStation: "River station", tresBocas: "Tres Bocas", abraVieja: "Abra Vieja stream", hornero: "El Hornero",
    directionsEyebrow: "04 — Directions", directionsTitle: "The journey is part of the outing.", directionsBody: "Reach Tigre and continue by water towards Tres Bocas, on the Abra Vieja stream. Check routes, schedules and availability with operators before travelling.", routeMapCaption: "Access map to Tres Bocas", mitre: "Mitre train", mitreDesc: "Travel from Retiro to Tigre station.", coast: "Tren de la Costa", coastDesc: "Travel to Delta station in Tigre.", car: "Car", carDesc: "Travel overland to Tigre and continue the route from there.", boatOption: "Public boat", boatDesc: "Interisleña · Ticket offices 3 and 4 · Get off at Tres Bocas", boatPhone: "Phone: 4749-0900", privateBoat: "Private water taxi", privateBoatDesc: "Arrange a private transfer to Tres Bocas.", privateBoatCta: "Arrange via WhatsApp", privateTransferEyebrow: "The journey is part of the plan", privateTransferTitle: "Arrive by river, at your own pace.", privateTransferBody: "Arrange a private water taxi to reach Tres Bocas directly and enjoy the scenery from the very start. Ask us about availability and we will plan the trip with you.", privateTransferCta: "Ask about a private transfer", viewStation: "View station", viewRiverStation: "View river station", maps: "Open in Google Maps", transportNote: "Services may change. Confirm travel information before setting out.",
    instagramTitle: "The Delta, in pictures", instagramCta: "View Instagram", footerLine: "Tigre Delta · Tres Bocas · Abra Vieja stream · Buenos Aires", backHome: "Back to home", menuPageTitle: "Menu", menuPageIntro: "Our digital menu", menuUpdated: "Configurable content", menuSample: "Sample menu", menuSampleNote: "The dishes, ingredients and availability on this menu are examples and should be confirmed with the restaurant.", noScript: "Enable JavaScript to use language selection and the gallery."
  },
  pt: {
    skip: "Pular para o conteúdo", navLabel: "Navegação principal", logoHome: "El Hornero, início", galleryDialog: "Galeria de imagens", deltaLandscape: "Paisagem do Delta", routeLabel: "Buenos Aires, Tigre Centro, lancha, Tres Bocas, Arroyo Abra Vieja, El Hornero", home: "Início", experience: "Experiência", menu: "Cardápio", gallery: "Galeria", directions: "Como chegar",
    language: "Escolher idioma", openMenu: "Abrir menu", closeMenu: "Fechar menu", heroKicker: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja", heroLine: "Uma mesa entre o rio e o verde.", viewMenu: "Ver cardápio", getThere: "Como chegar",
    expEyebrow: "01 — Experiência", expTitle: "O Delta, servido no seu próprio ritmo.", expBody: "Comida, madeira, vegetação e ar de rio se encontram em Tres Bocas. El Hornero propõe uma pausa simples dentro da paisagem do Delta.", expNote: "Um lugar para ficar um pouco",
    breakPhrase: "Entre glicínias, madeira e luz do Delta.",
    galleryEyebrow: "02 — Caderno de campo", galleryTitle: "Postais de Tres Bocas", galleryIntro: "Um olhar sobre os sabores, a paisagem e os pequenos detalhes ao redor da mesa.", viewImage: "Abrir imagem",
    catPlace: "O lugar", catFood: "Comida", catDelta: "Delta", catDetails: "Detalhes", catAtmosphere: "Atmosfera",
    altHero: "Mesa externa do El Hornero entre a vegetação do Delta de Tigre", altTable: "Espaço externo do El Hornero junto ao rio no Delta", altFood: "Prato servido no restaurante El Hornero no Delta", altRiver: "Paisagem do rio no Delta de Tigre perto do El Hornero", altPath: "Vegetação e trilhas do Delta de Tigre", altDetail: "Detalhes de madeira, vegetação e luz no El Hornero", altTerrace: "Mesas ao ar livre sob as árvores do Delta", altBoat: "Lancha navegando pelo Delta de Tigre", altPrivateBoat: "Passageiros viajando de lancha pelo Delta", altPrivateDestination: "Grupo de visitantes no El Hornero", altLight: "Luz entre glicínias, madeira e vegetação do Delta", altMenu: "Prato do cardápio do El Hornero no Delta", altGalleryPhoto: "Fotografia do restaurante El Hornero no Delta de Tigre", altRouteMap: "Mapa de acesso a Tres Bocas e El Hornero a partir de Tigre",
    lbClose: "Fechar galeria", lbPrev: "Imagem anterior", lbNext: "Próxima imagem",
    menuEyebrow: "03 — O cardápio", menuTitle: "Comer entre o verde", menuIntro: "Conheça nosso cardápio de exemplo e suas categorias.", openFullMenu: "Abrir cardápio completo", menuEmpty: "O cardápio ainda não foi carregado.", menuEmptyHint: "Consulte no local a proposta disponível.",
    journeyEyebrow: "Guia de viagem", journeyTitle: "Da Buenos Aires urbana ao Delta", journeyBody: "De Palermo, San Telmo, Microcentro ou La Boca, a paisagem muda ao se aproximar de Tigre. De lá, a lancha continua até Tres Bocas, pelo Arroyo Abra Vieja.", buenosAires: "Buenos Aires", tigreCenter: "Tigre Centro", boat: "Lancha", riverStation: "Estação fluvial", tresBocas: "Tres Bocas", abraVieja: "Arroyo Abra Vieja", hornero: "El Hornero",
    directionsEyebrow: "04 — Como chegar", directionsTitle: "O caminho também faz parte do passeio.", directionsBody: "Chegue a Tigre e continue pela água até Tres Bocas, no Arroyo Abra Vieja. Verifique rotas, frequências e disponibilidade com os operadores antes de viajar.", routeMapCaption: "Mapa de acesso a Tres Bocas", mitre: "Trem Mitre", mitreDesc: "Viaje de Retiro até a estação Tigre.", coast: "Tren de la Costa", coastDesc: "Viaje até a estação Delta, em Tigre.", car: "Carro", carDesc: "Chegue por terra até Tigre e continue o percurso de lá.", boatOption: "Lancha Pública", boatDesc: "Interisleña · Bilheterias 3 e 4 · Desembarque em Tres Bocas", boatPhone: "Telefone: 4749-0900", privateBoat: "Lancha Remis", privateBoatDesc: "Agende um traslado privado até Tres Bocas.", privateBoatCta: "Agendar pelo WhatsApp", privateTransferEyebrow: "A viagem também faz parte do passeio", privateTransferTitle: "Chegue pelo rio, no seu ritmo.", privateTransferBody: "Agende uma lancha remis para chegar diretamente a Tres Bocas e aproveitar a paisagem desde o primeiro momento. Consulte a disponibilidade e organizamos a viagem com você.", privateTransferCta: "Consultar traslado privado", viewStation: "Ver estação", viewRiverStation: "Ver estação fluvial", maps: "Abrir no Google Maps", transportNote: "Os serviços podem mudar. Confirme as informações de viagem antes de sair.",
    instagramTitle: "O Delta, em imagens", instagramCta: "Ver Instagram", footerLine: "Tigre Delta · Tres Bocas · Arroyo Abra Vieja · Buenos Aires", backHome: "Voltar ao início", menuPageTitle: "Cardápio", menuPageIntro: "Nosso cardápio digital", menuUpdated: "Conteúdo configurável", menuSample: "Cardápio de exemplo", menuSampleNote: "Os pratos, ingredientes e a disponibilidade deste cardápio são exemplos e devem ser confirmados com o restaurante.", noScript: "Ative o JavaScript para usar o seletor de idioma e a galeria."
  }
};
